language: php

php:
  - 7.2

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate:refresh --seed
  - php artisan passport:install
  - php artisan serve --host=0.0.0.0 --port=8000

script:
  
