version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
    - ./:/var/www
    env_file: .env
    environment:
    - "DB_PORT=3306"
    - "DB_HOST=database"
    - "DB_USER=root"
    - "DB_PASSWORD=root"
    ports:
    - "8000:80"
    - "443:80"
    - "8080:80"
    command: bash -c 'php artisan migrate && php artisan serve --host 0.0.0.0'
    depends_on:
    - database
    tty: true
  # The Web Server
  #  web:
  #    build:
  #      context: ./
  #      dockerfile: web.dockerfile
  #    working_dir: /var/www
  #    volumes_from:
  #    - app
  #    ports:
  #    - 8080:80
  # redis
  cache:
    image: redis:3.0-alpine
  # The Database
  database:
    image: mysql:5.6
    volumes:
    - dbdata:/var/lib/mysql
    environment:
    - "MYSQL_DATABASE=laravel"
    - "MYSQL_USER=root"
    - "MYSQL_PASSWORD=root"
    - "MYSQL_ROOT_PASSWORD=root"
    ports:
    - "3306:3306"

volumes:
  dbdata:
